name: Coverage Report

on:
  workflow_dispatch:

jobs:
  code-coverage:
    runs-on: macos-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"

      - name: 🧪 Run tests with coverage
        run: |
          swift test --enable-code-coverage --enable-test-discovery

      - name: 📊 Export LCOV format
        run: |
          mkdir -p coverage
          xcrun llvm-cov export             -format=lcov             .build/debug/PodcastFeedMakerPackageTests.xctest/Contents/MacOS/PodcastFeedMakerPackageTests             -instr-profile .build/debug/codecov/default.profdata             > coverage/coverage.lcov

      - name: 📤 Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-lcov
          path: coverage/coverage.lcov
